_target_: experiments.tagging.wrappers.TransformerWrapper
in_channels: null
out_channels: null
use_amp: false
attention_backend: xformers
mean_aggregation: true
zeropad: false

net:
 _target_: lloca.backbone.transformer.Transformer
 _partial_: true

 in_channels: null
 attn_reps: "8x0n+2x1n" # reps can be varied, but number of channels should stay fixed
 out_channels: null

 num_blocks: 10
 num_heads: 8
 mlp_factor: 4
 dropout_prob: null

 checkpoint_blocks: false
 compile: true
 compile_kwargs:
  dynamic: true
  mode: default

defaults:
 - framesnet: identity
