exp_type: atlastop
exp_name: atlastop

data:
 data_dir: data/atlastop/
 features: fourmomenta
 eval_systs: true
 systs_set:
  - all

 # miniweaver options
 config: null
 train_files_range: [0, 918]
 test_files_range: [0, 104]
 val_files_range: [918, 929]
 fraction_of_file: 1
 num_workers: 4
 fetch_step: 0.01
 extra_selection: null
 fetch_by_files: false
 in_memory: False
 not_remake_weights: False
 steps_per_epoch: null
 events_per_file: 100000
 async_load: true

evaluation:
 eval_set: [test]

plotting:
 roc: true
 score: true

defaults:
 - tagging
 - _self_
 - training: jc_transformer
