exp_type: jetset
exp_name: jetset

data:
 data_dir: data/jetset
 features: all
 tanh_scalars: true

 # miniweaver options
 config: null
 train_files_range: [0, 1684]
 test_files_range: [0, 256]
 val_files_range: [0, 56]
 fraction_of_file: 1
 num_workers: 2
 fetch_step: 5
 extra_selection: null
 fetch_by_files: true
 in_memory: False
 not_remake_weights: False
 steps_per_epoch: null
 events_per_file: 100000
 async_load: false

evaluation:
 eval_set: [test]

defaults:
 - training: jc_transformer
 - tagging
 - _self_
