exp_type: toptagxl
exp_name: toptagxl

data:
 data_dir: data/toptagxl
 features: fourmomenta

 # miniweaver options
 config: null
 train_files_range: [0, 500]
 test_files_range: [500, 625]
 val_files_range: [625, 650]
 fraction_of_file: 1
 num_workers: 2
 fetch_step: 0.01
 extra_selection: null
 fetch_by_files: false
 in_memory: False
 not_remake_weights: False
 steps_per_epoch: null
 events_per_file: 100000
 async_load: false

evaluation:
 eval_set: [test]

defaults:
 - training: jc_transformer
 - tagging
 - _self_
